title: Space Maze
hero_image: images/banner.png
description: Guide your astronauts back to Earth
original_url: 
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: scratch
hardware: ''
software: scratch
site_areas: projects
version: 4.0.1
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Setting up your project
- title: Leaving the ISS
- title: Heading home
- title: Avoiding the junk
- title: Permission to land
- title: What next?
